Add UA Iifo monitor
CanonicalLtd/landscape-client pull request #118
Opened 2022-10-07 17:54 UTC by Perfect5th

2022-12-08 17:48 UTC, silverdrake11 commented
This looks good. The only thing I noticed is the run_interval is missing. It's using the default I think which is too frequent. Should be like once every 60 or 15 minutes.

2022-12-14 00:04 UTC, Perfect5th commented
I think 15 minutes makes sense. It's pretty CPU-light, so more frequent than 60 minutes is ok.

As for that bug... I'm not overly concerned. I doubt it'll happen often, and re-registering isn't the end of the world. As you said, it won't matter once the full pro changes are in place.

2022-12-14 17:52 UTC, silverdrake11 requested changes

2022-12-14 17:52 UTC, silverdrake11 commented on landscape/client/monitor/ubuntuproinfo.py
> +    run_interval = 15
Should be 900 seconds

2022-12-14 23:23 UTC, Perfect5th commented on landscape/client/monitor/ubuntuproinfo.py
> +    run_interval = 15
oops - fixed.

2022-12-14 23:32 UTC, silverdrake11 approved these changes
LGTM +1

2022-12-14 23:37 UTC, merged