initial SnapMonitor and SnapManager implementations - installation and removal only
CanonicalLtd/landscape-client pull request #157
Opened 2023-04-18 23:31 UTC by Perfect5th

2023-04-18 23:31 UTC, Perfect5th commented
Let me know if you want to manually test and I can provide instructions (requires a private branch of Landscape Server that I've been working on in parallel).

2023-04-21 19:57 UTC, silverdrake11 requested changes

2023-04-21 19:57 UTC, silverdrake11 commented on landscape/client/deployment.py
> +            default=30 * 60,
Could be 15 minutes. It's cached

2023-04-21 19:57 UTC, silverdrake11 commented on landscape/client/deployment.py
> +            default=30 * 60,
Actually looking at the output, looks like there are timestamps in there. So best to strip them out so DataWatcher can cache the output and it's not sent every n minutes. Although the KeyDict selects the needed values, the caching should happen before

2023-04-21 19:57 UTC, silverdrake11 commented on landscape/client/manager/snapmanager.py
> +        Removes the snaps indicated in `message` using the snap interface.
This function is very similar to _install_snaps, so some code could be reused

2023-04-21 19:57 UTC, silverdrake11 commented on landscape/client/manager/snapmanager.py
> +        def get_status():
Found there's a twisted LoopingCallWithCount so I think  it passes an integer like `get_status(count)` so can get rid of the manual counter increment

2023-04-21 19:57 UTC, silverdrake11 commented on landscape/client/manager/snapmanager.py
> +        logging.info("Installing snaps: %s", snaps)
"{}".format or f-string is preferable

2023-04-21 19:57 UTC, silverdrake11 commented on landscape/client/manager/snapmanager.py
> +            logging.debug("Polling snapd for status of change %s", change_id)
Some of these could be in, info(), would make it easier to go through broker.log since, debug is not enabled by default

2023-04-21 19:57 UTC, silverdrake11 commented on landscape/client/monitor/snapmonitor.py
> +            snaps = self._snap_http.get_snaps()
See comment about caching

2023-04-21 19:57 UTC, silverdrake11 commented on landscape/client/snap/http.py
> +        curl, buff = self._setup_curl(path)
Could some of these steps be in the init and self.curl be used?

2023-04-21 19:57 UTC, silverdrake11 commented on landscape/client/snap/http.py
> +        """Removes a snap by `name`."""
Comment is not needed

2023-04-21 19:57 UTC, silverdrake11 commented on landscape/lib/schema.py
> +                    "%r is not a valid key as per %r" % (k, self.schema),
.format() is preferable

2023-05-30 18:51 UTC, closed without merging